contact_links:
  - name: Question ğŸ™‹
    url: https://discord.gg/qTPfvMxzNH
    about: Ask your question or suggestion in Discord server
  
  - name: Consumet extensions ğŸ”
    url: https://consumet.org/extensions/list/
    about: A list of the available providers
  
  - name: Consumet website
    url: https://consumet.org/docs/help
    about: Guides, And answer to common questions